"""init

Revision ID: 6597c31fa2f1
Revises:
Create Date: 2024-02-29 23:47:54.517789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6597c31fa2f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MALE', 'FEMALE', name='gender').create(op.get_bind())
    sa.Enum('EN', 'UK', name='language').create(op.get_bind())
    op.create_table('congratulations',
    sa.Column('photo_file_id', sa.String(), nullable=False),
    sa.Column('language', postgresql.ENUM('EN', 'UK', name='language', create_type=False), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_congratulations'))
    )
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', postgresql.ENUM('EN', 'UK', name='language', create_type=False), nullable=False),
    sa.Column('collect', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender', create_type=False), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('usergrouplink',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_usergrouplink_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usergrouplink_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'id', name=op.f('pk_usergrouplink'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usergrouplink')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('congratulations')
    sa.Enum('EN', 'UK', name='language').drop(op.get_bind())
    sa.Enum('MALE', 'FEMALE', name='gender').drop(op.get_bind())
    # ### end Alembic commands ###
