"""Added congratulation language

Revision ID: da415202154f
Revises: 9c1c66c0a6a8
Create Date: 2023-08-19 15:58:58.226068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da415202154f'
down_revision = '9c1c66c0a6a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congratulations', sa.Column('language', sa.Enum('EN', 'UA', name='language'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congratulations', 'language')
    # ### end Alembic commands ###
