name: 'Install Python and dependencies'

description: 'Set up Python and dependencies'
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: yezz123/setup-uv@v4
      with:
        uv-venv: ".venv"
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('requirements-dev.lock') }}
    - name: Install the project dependencies
      shell: bash
      run: uv pip install -r requirements-dev.lock
